_target_: lcvn_ac.datasets.social_disk_dataset.SocialDiskDataset
key: "lang"
save_format: "npz"
batch_size: ${datamodule.batch_size}
min_window_size: ${datamodule.min_window_size}
max_window_size: ${datamodule.seq_len}
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
skip_frames: 10
pad: true
for_wm: false
lang_folder: "lang_paraphrase-MiniLM-L3-v2"
aux_lang_loss_window: 1
num_workers: ${datamodule.num_workers}
